<?php
namespace App\Http\Controllers\Api\Delivery;

use App\Http\Controllers\ApiController;
use App\Models\{DeliveryTrip, DeliveryTripStop, Employee, Order};
use App\Services\Operations\OrderExecutionService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;

class DeliveryTripController extends ApiController
{
    public function __construct(private readonly OrderExecutionService $events) {}

    private function branch(Request $request): ?int { return $request->user()?->hasRole('super-admin') ? ($request->integer('branch_id') ?: null) : $request->user()?->branch_id; }
    private function assertTripBranch(Request $request, DeliveryTrip $trip): void { abort_unless($request->user()?->hasRole('super-admin') || (int) $request->user()?->branch_id === (int) $trip->branch_id, 403, 'لا يمكنك الوصول إلى رحلة فرع آخر'); }
    private function load(DeliveryTrip $trip): DeliveryTrip { return $trip->load(['branch:id,name','driver:id,name,phone,vehicle_type','stops.order.deliveryDriver','stops.order.deliveryZone']); }

    public function index(Request $request) { $q=DeliveryTrip::with(['driver:id,name','branch:id,name'])->withCount('stops')->when($this->branch($request),fn($x,$id)=>$x->where('branch_id',$id))->when($request->status,fn($x,$v)=>$x->where('status',$v))->latest(); return $this->success('Delivery trips fetched',$q->paginate(min(100,max(10,$request->integer('per_page',25))))); }
    public function candidates(Request $request) { $q=Order::with(['customer','deliveryZone'])->where('order_type','delivery')->where('status',Order::STATUS_READY_FOR_DELIVERY)->whereNotNull('assembled_at')->whereNull('driver_id')->whereDoesntHave('deliveryTripStops',fn($x)=>$x->whereHas('trip',fn($t)=>$t->whereNotIn('status',['completed','cancelled'])))->when($this->branch($request),fn($x,$id)=>$x->where('branch_id',$id))->oldest('assembled_at'); return $this->success('Candidate orders fetched',$q->paginate(min(100,max(10,$request->integer('per_page',50))))); }

    public function store(Request $request) {
        $data=$request->validate(['branch_id'=>['nullable','integer','exists:branches,id'],'driver_id'=>['nullable','integer','exists:employees,id'],'notes'=>['nullable','string','max:2000'],'order_ids'=>['required','array','min:1','max:'.config('call_center.trip_max_stops',3)],'order_ids.*'=>['integer','distinct','exists:orders,id']]);
        $trip=DB::transaction(function() use($data,$request) { $orders=Order::whereIn('id',$data['order_ids'])->lockForUpdate()->get(); $branch=$request->user()?->hasRole('super-admin')?(int)$orders->first()?->branch_id:(int)$request->user()?->branch_id; abort_unless($branch,422,'تعذر تحديد فرع الطلبات'); $this->assertOrders($orders,$branch); $this->assertDriver($data['driver_id']??null,$branch); $trip=DeliveryTrip::create(['branch_id'=>$branch,'driver_id'=>$data['driver_id']??null,'number'=>'TRIP-'.now()->format('Ymd').'-'.str_pad((string)(DeliveryTrip::max('id')+1),4,'0',STR_PAD_LEFT),'status'=>'draft','notes'=>$data['notes']??null,'created_by'=>$request->user()?->id]); $this->replaceStops($trip,$orders,$data['order_ids']); return $trip; });
        return $this->success('Delivery trip created',$this->load($trip));
    }
    public function show(Request $request,DeliveryTrip $deliveryTrip) { $this->assertTripBranch($request,$deliveryTrip); return $this->success('Delivery trip fetched',$this->load($deliveryTrip)); }
    public function update(Request $request,DeliveryTrip $deliveryTrip) { $this->assertTripBranch($request,$deliveryTrip); abort_unless($deliveryTrip->status==='draft',422,'يمكن تعديل الرحلة في المسودة فقط'); $data=$request->validate(['driver_id'=>['nullable','integer','exists:employees,id'],'notes'=>['nullable','string','max:2000'],'order_ids'=>['nullable','array','min:1'],'order_ids.*'=>['integer','distinct','exists:orders,id']]); DB::transaction(function() use($deliveryTrip,$data) { $trip=DeliveryTrip::lockForUpdate()->findOrFail($deliveryTrip->id); $this->assertDriver($data['driver_id']??$trip->driver_id,$trip->branch_id); $trip->update(collect($data)->only(['driver_id','notes'])->all()); if(isset($data['order_ids'])) { $orders=Order::whereIn('id',$data['order_ids'])->lockForUpdate()->get(); $this->assertOrders($orders,$trip->branch_id,$trip->id); $this->replaceStops($trip,$orders,$data['order_ids']); } }); return $this->success('Delivery trip updated',$this->load($deliveryTrip->fresh())); }

    public function ready(Request $request,DeliveryTrip $deliveryTrip) { $this->assertTripBranch($request,$deliveryTrip); DB::transaction(function() use($deliveryTrip) { $trip=DeliveryTrip::lockForUpdate()->findOrFail($deliveryTrip->id); abort_unless($trip->status==='draft',422,'يمكن تجهيز الرحلة من المسودة فقط'); abort_unless($trip->driver_id,422,'اختر المندوب'); abort_unless($trip->stops()->exists(),422,'أضف طلباً واحداً على الأقل'); $this->assertDriver($trip->driver_id,$trip->branch_id); $trip->update(['status'=>'ready']); }); return $this->success('Delivery trip ready',$this->load($deliveryTrip->fresh())); }
    public function addStop(Request $request,DeliveryTrip $deliveryTrip) { $this->assertTripBranch($request,$deliveryTrip); abort_unless($deliveryTrip->status==='draft',422,'يمكن تعديل محطات الرحلة في المسودة فقط'); abort_if($deliveryTrip->stops()->count()>=$deliveryTrip->max_stops,422,'وصلت الرحلة إلى الحد الأقصى للمحطات'); $data=$request->validate(['order_id'=>['required','integer','exists:orders,id']]); DB::transaction(function() use($deliveryTrip,$data) { $order=Order::lockForUpdate()->findOrFail($data['order_id']); $this->assertOrders(collect([$order]),$deliveryTrip->branch_id,$deliveryTrip->id); $deliveryTrip->stops()->create(['order_id'=>$order->id,'sequence'=>($deliveryTrip->stops()->max('sequence')??0)+1,'delivery_address_snapshot'=>$order->delivery_address_snapshot]); }); return $this->success('Delivery stop added',$this->load($deliveryTrip->fresh())); }
    public function removeStop(Request $request,DeliveryTrip $deliveryTrip,DeliveryTripStop $stop) { $this->assertTripBranch($request,$deliveryTrip); abort_unless($deliveryTrip->status==='draft',422,'يمكن تعديل محطات الرحلة في المسودة فقط'); abort_unless((int)$stop->delivery_trip_id===(int)$deliveryTrip->id,404); abort_unless($deliveryTrip->stops()->count()>1,422,'يجب أن تحتوي الرحلة على طلب واحد على الأقل'); $stop->delete(); $this->normalizeSequence($deliveryTrip); return $this->success('Delivery stop removed',$this->load($deliveryTrip->fresh())); }
    public function reorder(Request $request,DeliveryTrip $deliveryTrip) { $this->assertTripBranch($request,$deliveryTrip); abort_unless($deliveryTrip->status==='draft',422,'يمكن ترتيب المحطات في المسودة فقط'); $data=$request->validate(['stop_ids'=>['required','array','min:1'],'stop_ids.*'=>['integer','distinct']]); $current=$deliveryTrip->stops()->pluck('id')->sort()->values()->all(); $given=collect($data['stop_ids'])->sort()->values()->all(); abort_unless($current===$given,422,'يجب إرسال جميع محطات الرحلة مرة واحدة'); DB::transaction(fn()=>collect($data['stop_ids'])->each(fn($id,$i)=>DeliveryTripStop::whereKey($id)->where('delivery_trip_id',$deliveryTrip->id)->update(['sequence'=>$i+1]))); return $this->success('Delivery stops reordered',$this->load($deliveryTrip->fresh())); }

    public function start(Request $request,DeliveryTrip $deliveryTrip) { $this->assertTripBranch($request,$deliveryTrip); $trip=DB::transaction(function() use($deliveryTrip,$request) { $trip=DeliveryTrip::lockForUpdate()->findOrFail($deliveryTrip->id); abort_unless(in_array($trip->status,['draft','ready'],true),422,'الرحلة ليست جاهزة للبدء'); $this->assertDriver($trip->driver_id,$trip->branch_id); $driver=Employee::lockForUpdate()->findOrFail($trip->driver_id); abort_if(DeliveryTrip::where('driver_id',$driver->id)->whereIn('status',DeliveryTrip::ACTIVE)->whereKeyNot($trip->id)->exists(),422,'المندوب في رحلة نشطة'); $stops=$trip->stops()->with('order')->lockForUpdate()->get(); $this->assertOrders($stops->pluck('order'),$trip->branch_id,$trip->id); foreach($stops as $stop){$this->events->startDelivery($stop->order,$driver,$request->user(),$trip);$stop->update(['status'=>'out_for_delivery']);} $trip->update(['status'=>'in_progress','started_at'=>now()]); return $trip; },3); return $this->success('Delivery trip started',$this->load($trip)); }
    public function stop(Request $request,DeliveryTrip $deliveryTrip,DeliveryTripStop $stop) { $this->assertTripBranch($request,$deliveryTrip); abort_unless((int)$stop->delivery_trip_id===(int)$deliveryTrip->id,404); $data=$request->validate(['status'=>['required','in:delivered,failed'],'notes'=>['nullable','string','max:2000'],'failure_reason'=>['nullable','required_if:status,failed','string','max:2000']]); DB::transaction(function() use($deliveryTrip,$stop,$data,$request) { $trip=DeliveryTrip::lockForUpdate()->findOrFail($deliveryTrip->id); abort_unless($trip->status==='in_progress',422,'الرحلة ليست قيد التنفيذ'); $locked=DeliveryTripStop::lockForUpdate()->findOrFail($stop->id); abort_unless($locked->status==='out_for_delivery',422,'تم إغلاق المحطة'); $order=Order::lockForUpdate()->findOrFail($locked->order_id); if($data['status']==='delivered') $this->events->completeDelivery($order,$trip->driver,$request->user(),$trip,$data['notes']??null); else {$order->update(['status'=>Order::STATUS_FAILED_DELIVERY]);$this->events->recordEvent($order,'delivery_stop_failed',$trip->driver,$request->user(),$data['failure_reason'],['delivery_trip_id'=>$trip->id]);} $locked->update(['status'=>$data['status'],'delivered_at'=>$data['status']==='delivered'?now():null,'failed_at'=>$data['status']==='failed'?now():null,'notes'=>$data['notes']??null,'failure_reason'=>$data['failure_reason']??null]); if(!$trip->stops()->whereNotIn('status',['delivered','failed','cancellation_requested','cancelled'])->exists()) $trip->update(['status'=>'completed','completed_at'=>now()]); },3); return $this->success('Delivery stop updated',$this->load($deliveryTrip->fresh())); }
    public function cancel(Request $request,DeliveryTrip $deliveryTrip) { $this->assertTripBranch($request,$deliveryTrip); DB::transaction(function() use($deliveryTrip,$request) { $trip=DeliveryTrip::lockForUpdate()->findOrFail($deliveryTrip->id); abort_if(in_array($trip->status,['completed','cancelled'],true),422,'لا يمكن إلغاء هذه الرحلة'); abort_if($trip->stops()->where('status','delivered')->exists(),422,'لا يمكن إلغاء رحلة بعد تسليم محطة'); if($trip->status==='in_progress') foreach($trip->stops()->with('order')->where('status','pending')->get() as $stop) $this->events->recoverDelivery($stop->order,$request->user(),$trip); $trip->stops()->where('status','pending')->update(['status'=>'skipped']); $trip->update(['status'=>'cancelled']); }); return $this->success('Delivery trip cancelled',$this->load($deliveryTrip->fresh())); }

    private function assertDriver(?int $driverId,int $branch):void { if(!$driverId) return; $driver=Employee::lockForUpdate()->findOrFail($driverId); abort_unless((int)$driver->branch_id===$branch,422,'المندوب يجب أن يكون من فرع الرحلة'); abort_unless($driver->operational_role==='delivery_driver'&&$driver->is_operations_enabled&&$driver->status==='ACTIVE'&&filled($driver->vehicle_type),422,'المندوب غير متاح أو بلا مركبة'); }
    private function assertOrders($orders,int $branch,?int $tripId=null):void { if($orders->isEmpty()) throw ValidationException::withMessages(['order_ids'=>'اختر طلباً واحداً على الأقل']); if($orders->count()>config('call_center.trip_max_stops',3)) throw ValidationException::withMessages(['order_ids'=>'الحد الأقصى ثلاث طلبات']); foreach($orders as $order) { if((int)$order->branch_id!==$branch||$order->order_type!=='delivery'||$order->status!==Order::STATUS_READY_FOR_DELIVERY||!$order->assembled_at||$order->driver_id) throw ValidationException::withMessages(['order_ids'=>'أحد الطلبات غير جاهز أو من فرع آخر']); $busy=DeliveryTripStop::where('order_id',$order->id)->whereHas('trip',fn($q)=>$q->whereNotIn('status',['completed','cancelled'])->when($tripId,fn($x)=>$x->whereKeyNot($tripId)))->exists(); if($busy) throw ValidationException::withMessages(['order_ids'=>'أحد الطلبات موجود في رحلة نشطة']); } }
    private function replaceStops(DeliveryTrip $trip,$orders,array $ids):void { $trip->stops()->delete(); foreach($ids as $i=>$id) { $order=$orders->firstWhere('id',$id); $trip->stops()->create(['order_id'=>$id,'sequence'=>$i+1,'delivery_address_snapshot'=>$order->delivery_address_snapshot]); } }
    private function normalizeSequence(DeliveryTrip $trip):void { $trip->stops()->get()->values()->each(fn($stop,$i)=>$stop->update(['sequence'=>$i+1])); }
}
