<?php
namespace App\Http\Controllers\Api\Delivery;
use App\Http\Controllers\ApiController;
use App\Models\DeliveryZone;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
class DeliveryZoneController extends ApiController
{
    private function branchId(Request $r):?int{return $r->user()?->hasRole('super-admin')?($r->integer('branch_id')?:null):$r->user()?->branch_id;}
    public function index(Request $r){$q=DeliveryZone::with('branch:id,name')->when($this->branchId($r),fn($x,$id)=>$x->where('branch_id',$id))->when($r->filled('search'),fn($x)=>$x->where(fn($y)=>$y->where('name','like','%'.$r->search.'%')->orWhere('code','like','%'.$r->search.'%')->orWhere('city','like','%'.$r->search.'%')->orWhere('area','like','%'.$r->search.'%')))->when($r->has('active'),fn($x)=>$x->where('is_active',$r->boolean('active')))->latest();return $this->success('Delivery zones fetched',$q->paginate(min(100,max(10,$r->integer('per_page',25)))));}
    public function store(Request $r){return $this->saveZone($r,new DeliveryZone);}
    public function update(Request $r,DeliveryZone $deliveryZone){$this->assertBranch($r,$deliveryZone->branch_id);return $this->saveZone($r,$deliveryZone);}
    private function saveZone(Request $r,DeliveryZone $z){$branch=$r->user()?->hasRole('super-admin')?$r->integer('branch_id'):$r->user()?->branch_id;abort_unless($branch,422,'يجب تحديد الفرع');if($z->exists)abort_unless((int)$z->branch_id===(int)$branch,403);$d=$r->validate(['code'=>['required','string','max:50',Rule::unique('delivery_zones')->where('branch_id',$branch)->ignore($z->id)],'name'=>['required','string','max:255'],'city'=>['nullable','string','max:120'],'area'=>['nullable','string','max:120'],'base_fee'=>['required','numeric','min:0'],'minimum_order_amount'=>['nullable','numeric','min:0'],'free_delivery_threshold'=>['nullable','numeric','min:0'],'estimated_minutes'=>['nullable','integer','min:1','max:1440'],'is_active'=>['boolean'],'notes'=>['nullable','string','max:2000']]);$z->fill($d+['branch_id'=>$branch])->save();return $this->success('Delivery zone saved',$z->load('branch:id,name'));}
    public function destroy(Request $r,DeliveryZone $deliveryZone){$this->assertBranch($r,$deliveryZone->branch_id);abort_if($deliveryZone->orders()->exists(),409,'المنطقة مستخدمة في طلبات');$deliveryZone->delete();return $this->success('Delivery zone deleted');}
    public function quote(Request $r){$d=$r->validate(['branch_id'=>['nullable','integer','exists:branches,id'],'delivery_zone_id'=>['nullable','integer','exists:delivery_zones,id'],'city'=>['nullable','string'],'area'=>['nullable','string'],'subtotal'=>['required','numeric','min:0']]);$branch=$r->user()?->hasRole('super-admin')?($d['branch_id']??null):$r->user()?->branch_id;$z=DeliveryZone::where('branch_id',$branch)->where('is_active',true)->when($d['delivery_zone_id']??null,fn($q,$id)=>$q->whereKey($id))->when(!($d['delivery_zone_id']??null)&&($d['city']??null),fn($q)=>$q->where('city',$d['city']))->when(!($d['delivery_zone_id']??null)&&($d['area']??null),fn($q)=>$q->where('area',$d['area']))->firstOrFail();$sub=(float)$d['subtotal'];$fee=$z->free_delivery_threshold!==null&&$sub>=(float)$z->free_delivery_threshold?0:(float)$z->base_fee;return $this->success('Delivery quote resolved',['zone'=>$z,'fee'=>$fee,'eligible'=>$z->minimum_order_amount===null||$sub>=(float)$z->minimum_order_amount]);}
    private function assertBranch(Request $r,int $branch):void{abort_unless($r->user()?->hasRole('super-admin')||(int)$r->user()?->branch_id===$branch,403,'لا يمكنك الوصول إلى بيانات فرع آخر');}
}
